### ISSUE TITLE
Allow em-dash in financial years for `fy2date()`

### ISSUE THREAD

**Issue by MattCowgill** [HughParsonage/fy#1]
``` r
my_fy <- "2014–15"
grattan::fy2date(my_fy)  
#> Error in grattan::fy2date(my_fy): fy.yr contains non-FYs
my_fy <- gsub("–", "-", my_fy)
grattan::fy2date(my_fy) 
#> [1] "2015-06-30"
```

<sup>Created on 2019-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by HughParsonage** [comment]
Yes good idea. Two subissues:

  1. Performance has proved to be a (surprisingly) big issue with these functions, so we'll need to ensure the method doesn't impinge too much on the very large cases with 'nice' fys. 
  2. I'm planning to hoist the `fy` functions into the [`fy`](https://github.com/hughparsonage/fy) package and import them into grattan, so that would be a better place for the work to commence.

**Comment by HughParsonage** [comment]
Let me know if the referenced PR works or not.

**Comment by MattCowgill** [comment]
Works perfectly, thanks @HughParsonage

**Comment by MattCowgill** [comment]
Minor issue: the "2014–15" form is not listed in the allowed forms in `?fy2date`

**Comment by HughParsonage** [comment]
In CRAN now
